name: Build and push docker image

on:
  push:
    branches:
      - 'UAB-*'
  workflow_dispatch:

jobs:
  BuildGuacamoleImage:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Branch a usar como variable de entorno
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: set NOW
        run: |
              cat $GITHUB_ENV
              echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
              cat $GITHUB_ENV

      - name: set REPO_NAME
        run: |
              cat $GITHUB_ENV
              echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
              cat $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USER }}/${{ env.REPO_NAME }}:${{ env.BRANCH }}-${{ env.NOW }}
          build-args: |
              BRANCH=${{ env.BRANCH }}
